# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app:
    build:
      context: .
      target: final
    environment:
      - JWT_SECRET=ChangeThisBeforeRunning
      - JWT_ACCESS_TOKEN_EXPIRED=1d
      - MONGODB_CONNECT_URI=mongodb://db:27017/kohi
    ports:
      - 8080:3000
    depends_on:
      - db
    networks:
      - kohi-data
    restart: always
  db:
    image: mongo:latest
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - kohi-data
    expose:
      - 27017

volumes:
  db-data:


networks:
  kohi-data:
